(setq auto-save-default nil)
(setq make-backup-files nil)
(setq auto-save-list-file-prefix nil)
(setq line-number-mode t)
(setq column-number-mode t)
(global-set-key "\C-h" `delete-backward-char)
(global-set-key "\C-\\" 'other-window)
(add-hook 'python-mode-hook
  (lambda ()
    (setq python-indent-offset 2)
    (setq indent-tabs-mode nil)))
(defun my-c++-mode-hook ()
  (c-set-offset 'innamespace 0))
(add-hook 'c++-mode-hook 'my-c++-mode-hook)
