# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias em='emacs -nw'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS="-iMR"
