# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias emacs='env TERM=xterm emacs'
alias em='emacs -nw'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias od='od -tx4z -Ax -v'

export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS="-iMR"
export PRINTER=C841dn

# Geant4
export G4WORKDIR=$HOME/share/geant4
. $G4WORKDIR/install/11.2.2/bin/geant4.sh 2>/dev/null
. $G4WORKDIR/install/11.2.2/share/Geant4/geant4make/geant4make.sh 2>/dev/null
